
services:
  api:
    build:
      context: .
      dockerfile: NovaSpace.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmentq
    
  client:
    build:
      context: .
      dockerfile: NovaSpace.Client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api